"""Initial migration

Revision ID: 88018c198478
Revises: 
Create Date: 2026-04-20 11:28:37.644291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88018c198478'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empleados',
    sa.Column('id_empleado', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('rol', sa.String(length=50), nullable=False),
    sa.Column('fecha_contratacion', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id_empleado'),
    sa.UniqueConstraint('email')
    )
    op.create_table('horarios',
    sa.Column('id_horario', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.String(length=20), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.PrimaryKeyConstraint('id_horario')
    )
    op.create_table('salas',
    sa.Column('id_sala', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('capacidad', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_sala')
    )
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('fecha_registro', sa.Date(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('email')
    )
    op.create_table('actividades',
    sa.Column('id_actividad', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('monitor_id', sa.Integer(), nullable=True),
    sa.Column('sala_id', sa.Integer(), nullable=True),
    sa.Column('horario_id', sa.Integer(), nullable=True),
    sa.Column('aforo_maximo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['horario_id'], ['horarios.id_horario'], ),
    sa.ForeignKeyConstraint(['monitor_id'], ['empleados.id_empleado'], ),
    sa.ForeignKeyConstraint(['sala_id'], ['salas.id_sala'], ),
    sa.PrimaryKeyConstraint('id_actividad')
    )
    op.create_table('materiales',
    sa.Column('id_material', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('sala_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sala_id'], ['salas.id_sala'], ),
    sa.PrimaryKeyConstraint('id_material')
    )
    op.create_table('pagos',
    sa.Column('id_pago', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha_pago', sa.Date(), nullable=True),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('metodo_pago', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_pago')
    )
    op.create_table('incidencias',
    sa.Column('id_incidencia', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('empleado_id', sa.Integer(), nullable=True),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.id_empleado'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materiales.id_material'], ),
    sa.PrimaryKeyConstraint('id_incidencia')
    )
    op.create_table('reservas',
    sa.Column('id_reserva', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('actividad_id', sa.Integer(), nullable=False),
    sa.Column('fecha_reserva', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['actividad_id'], ['actividades.id_actividad'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_reserva')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservas')
    op.drop_table('incidencias')
    op.drop_table('pagos')
    op.drop_table('materiales')
    op.drop_table('actividades')
    op.drop_table('usuarios')
    op.drop_table('salas')
    op.drop_table('horarios')
    op.drop_table('empleados')
    # ### end Alembic commands ###
