"""Add estado to Pago

Revision ID: e0d29ef4b1ef
Revises: 88018c198478
Create Date: 2026-04-22 10:08:51.411505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0d29ef4b1ef'
down_revision = '88018c198478'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.drop_column('estado')

    # ### end Alembic commands ###
